name: Setup
description: Install devbox and npm dependencies

runs:
  using: composite
  steps:
    - name: Install devbox
      uses: jetify-com/devbox-install-action@v0.12.0

    - name: Cache npm packages
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      run: devbox run npm ci
      shell: bash
