repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: build
        name: Build CSS and index.html
        entry: make build
        language: system
        types_or: [css, scss, html]
        pass_filenames: false
        stages: [pre-commit]
